language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y ragel zzuf

script:
  - cmake .
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 ctest .
  - ./test.sh

git:
  depth: 3

branches:
  only:
    - master