version: 1.0.{build}
configuration: Release
before_build:
- cmd: >-
    appveyor DownloadFile http://downloads.yorickpeterse.com/files/ragel-68-visualstudio2012.7z -FileName C:\ragel.7z

    7z e C:\ragel.7z -oC:\ragel -y > nul

    SET PATH=C:\ragel;%PATH%

    cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%P%
build:
  project: logpipe.sln
  verbosity: normal
artifacts:
- path: bin/logpipe.exe
